const RATES_LOAD = `RATES_LOAD`;
const RATES_FAILURE = `RATES_FAILURE`;
const BASE_CURRENCY_SET = `BASE_CURRENCY_SET`;
const USER_SETTINGS_LOAD = `USER_SETTINGS_LOAD`;
const FAVORITE_ADD = `FAVORITE_ADD`;
const FAVORITE_DELETE = `FAVORITE_DELETE`;

export default {
  RATES_LOAD,
  RATES_FAILURE,
  BASE_CURRENCY_SET,
  USER_SETTINGS_LOAD,
  FAVORITE_ADD,
  FAVORITE_DELETE
}
